name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.12'    # minimum supported version
          - '1'       # latest release
        # linux only: `pynormaliz` (via SymmetryBases) has no osx-arm64 or win-64 conda build
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      # `pymeep` is pulled in through MPBUtils via CondaPkg; installing it cold takes minutes
      - uses: actions/cache@v4
        with:
          path: .CondaPkg
          key: condapkg-${{ runner.os }}-${{ hashFiles('Project.toml') }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: AntonioMoralesPerez/PhotonicTightBinding.jl
